feat: add webpack.config.dev.js for local serving of remoteEntry.js
Consensys/starknet-snap pull request #243
Opened 2024-05-23 09:39 UTC by khanti42

Local serving of remoteEntry.js can be done with 

`yarn serve:fed` from the `packages/get-starknet` sub folder. 
Associated with https://github.com/Consensys/get-starknet/pull/13

2024-05-24 02:37 UTC, stanleyyconsensys requested changes
if we wanna setup a complete local dev env
we also need to make this get-starknet wrapper using a SNAP from local rather from prod

in order to do that
update `MetaMaskSnapWallet` class to change the const SNAPI_ID reading from env var , default is `npm:@consensys/starknet-snap`

file: wallet.ts
```javascript
private static readonly SNAPI_ID =  process.env.SNAP_ID ?? npm:@consensys/starknet-snap
```

file: .env
```bash
SNAPI_ID=local:http://localhost:8081
```

2024-05-24 02:37 UTC, stanleyyconsensys commented on packages/get-starknet/webpack.config.dev.js
> +const common = require('./webpack.common.js');
add // eslint-disable-next-line @typescript-eslint/no-var-requires for each require

2024-05-24 10:53 UTC, stanleyyconsensys approved these changes
LGTM

2024-06-07 13:16 UTC, closed without merging

2024-06-07 13:17 UTC, khanti42 commented
Check  [PR-249](https://github.com/Consensys/starknet-snap/pull/249) for update.