feat: show upgrade dialog on get-starknet calls
Consensys/starknet-snap pull request #247
Opened 2024-06-06 06:55 UTC by khanti42

2024-06-07 07:53 UTC, stanleyyconsensys requested changes

2024-06-07 07:53 UTC, stanleyyconsensys commented on packages/starknet-snap/src/declareContract.ts
> +      return false;
perhaps throw an error is better?
in terms of end user exp, we handle by dialog
in terms of the coding handle, return false may not fit to the purpose for the caller to determine it is success or not , throw an error seem more general 

WDYT

2024-06-07 07:54 UTC, stanleyyconsensys commented on packages/starknet-snap/src/declareContract.ts
> +      return false;
BTW , test is not pass

2024-06-07 08:19 UTC, stanleyyconsensys commented on packages/starknet-snap/src/declareContract.ts
> +      return false;
you have to await for showUpgradeRequestModal

2024-06-17 14:58 UTC, khanti42 commented
I already merged latest changes from main (including the deployment check for executeTxn), the PR#254 including these changes in release/2.3.0 is still open

2024-06-21 02:13 UTC, stanleyyconsensys approved these changes
LGTM

2024-06-21 08:11 UTC, stanleyyconsensys approved these changes

2024-06-21 13:19 UTC, merged