refactor: add `verifyIfAccountNeedUpgradeOrDeploy` method to group the deploy or upgrade validation logic
Consensys/starknet-snap pull request #311
Opened 2024-08-01 05:58 UTC by stanleyyconsensys

This PR is to add new method `verifyIfAccountNeedUpgradeOrDeploy`  in snapUtils to group the logic of
- show update/deploy alert dialog (optional)
- check if the account needed to upgrade or deploy
- throw upgrade or deploy required error

it also update the `showDeployRequestModal ` and `showUpgradeRequestModal ` to use the alertDialog utils from `snap`

2024-08-02 12:27 UTC, khanti42 requested changes
Just wondering regarding test cases that have been removed by the PR and their effect. Should we reduce the required test coverage on mocha in `starknet-snap/package.json` as some test are moved to jest ?

2024-08-02 12:27 UTC, khanti42 commented on packages/starknet-snap/test/src/declareContract.test.ts
We are reducing the test coverage on mocha, does that require to reduce the coverage limit in package.json to not break ci/cd ?

2024-08-06 01:02 UTC, stanleyyconsensys commented on packages/starknet-snap/test/src/declareContract.test.ts
good point, lets reduce the coverage

2024-08-06 01:07 UTC, stanleyyconsensys commented on packages/starknet-snap/test/src/declareContract.test.ts
i think it does not reduce many coverage, even i remove all the require deploy/upgrade checking

as in previous code, deploy/upgrade checking logic has to try catch on each file , so ur test code needed do the test on every file

but right now, i remove the try catch and move that into a share function `verifyIfAccountNeedUpgradeOrDeploy `
Therefore, in each file, this function will execute anyway, hence it has already replace the coverage

however, for the individual function `verifyIfAccountNeedUpgradeOrDeploy`  , we didnt do the test on mocha side but just the jest side, indeed it will reduce a bit on the coverage, but should be very very minor

2024-08-12 08:42 UTC, stanleyyconsensys commented on packages/starknet-snap/test/src/declareContract.test.ts
PR: https://github.com/Consensys/starknet-snap/pull/313

2024-08-12 10:22 UTC, khanti42 approved these changes

2024-08-12 10:50 UTC, merged