feat(get-starknet): add skeleton to support get-starknet v4
Consensys/starknet-snap pull request #365
Opened 2024-10-04 06:38 UTC by stanleyyconsensys

This PR is to update the get-starknet wrapper to support the latest get-starknet v4 implementation, but in the meanwhile also supporting the legacy(v3) implementation

the Major change of the implementation are:

- having a new method `Init` -> to update the v3 property (account object, provider object, selectedAddress and isConnected) when network is switching
- `fix` a bug when the network switch but the address remain the same

2024-10-04 10:57 UTC, khanti42 requested changes
Very minore changes, otherwise LGTM.

2024-10-04 10:57 UTC, khanti42 commented on packages/get-starknet/src/rpcs/switch-network.ts
> +      // The wallet.chainid should be always refer to the latest snap chain id
```suggestion
      // The wallet.chainid should always refer to the latest snap chain id
```

2024-10-04 12:28 UTC, stanleyyconsensys commented on packages/get-starknet/package.json
> +    "test": "jest --passWithNoTests"
the github action is already using 'yarn test' from root, so it is fine

2024-10-08 07:41 UTC, khanti42 approved these changes
LGTM

2024-10-08 07:42 UTC, merged