feat: refactor RPC `starkNet_getTransactions` with `StarkScan` DataClient
Consensys/starknet-snap pull request #453
Opened 2024-12-06 03:14 UTC by stanleyyconsensys

This PR is refactor RPC `starkNet_getTransactions` to switch the data provider from Voyager to StarkScan  

it includes:
- refactor RPC `starkNet_getTransactions` with new RPC structure.
- apply StarkScan into  `starkNet_getTransactions`.
- add `TransactionService` to encapsulate the logic for list transactions.
- the data provided by the provider will not be stored in the state. Only the transaction sent from the wallet UI will be stored until it is confirmed by the L2 Chain.

2024-12-06 15:11 UTC, khanti42 requested changes

2024-12-09 02:22 UTC, stanleyyconsensys commented on packages/starknet-snap/src/chain/transaction-service.ts
> +  protected isTransactionHasSameContractOrAnDeploy(
for boolean, we start with Is or has

2024-12-09 02:24 UTC, stanleyyconsensys commented on packages/starknet-snap/src/index.tsx
> +  ListTransactions,
good catch

2024-12-09 02:32 UTC, stanleyyconsensys commented on packages/starknet-snap/src/chain/transaction-service.ts
> +  protected isTransactionHasSameContractOrAnDeploy(
as it is in transaction service, so we know it is for transaction

may be rename it to 
`hasMatchingContractOrIsDeploy`?

wdyt?

2024-12-09 10:48 UTC, khanti42 requested changes

2024-12-09 10:48 UTC, khanti42 commented on packages/starknet-snap/src/chain/transaction-service.ts
> +  protected isTransactionHasSameContractOrAnDeploy(
hasMatchingContractOrIsDeploy works great!

2024-12-10 08:33 UTC, khanti42 approved these changes
LGTM

2024-12-10 08:34 UTC, merged