chore: wallet-ui send workflow allow return back
Consensys/starknet-snap pull request #468
Opened 2024-12-18 14:02 UTC by khanti42

Based on QA review, this PR introduces functionality that allows users to navigate back from the “Send Summary Modal View” to the “Send View” while retaining the address and value of the transaction. This ensures users can easily update the transaction parameters if needed without starting over.

2024-12-18 14:51 UTC, stanleyyconsensys requested changes

2024-12-18 14:51 UTC, stanleyyconsensys commented on packages/wallet-ui/src/components/ui/organism/Header/SendModal/SendModal.view.tsx
> +  useEffect(() => {}, [fields]);
what is the purpose to have the useEffect?

2024-12-18 14:51 UTC, stanleyyconsensys commented on packages/wallet-ui/src/components/ui/molecule/AmountInput/AmountInput.view.tsx
> +  }, [inputValue]);
```suggestion
  }, [inputValue, inputRef]);
```

2024-12-18 14:51 UTC, stanleyyconsensys commented on packages/wallet-ui/src/components/ui/molecule/AmountInput/AmountInput.view.tsx
> +    if (value && asset.usdPrice) {
not quite sure if this condition is correct, it look like u only do it when value is exist or > 0?

2024-12-19 03:20 UTC, stanleyyconsensys commented on packages/wallet-ui/src/components/ui/organism/Header/SendSummaryModal/SendSummaryModal.view.tsx
> +          onClick={() => handleBack(amount, address)}
```suggestion
          onClick={() => handleBack()}
```

2024-12-19 03:20 UTC, stanleyyconsensys commented on packages/wallet-ui/src/components/ui/organism/Header/SendModal/SendModal.view.tsx
> +  };
```suggestion
  const handleBack = () => {
    setSummaryModalOpen(false);
  };
```
setFields is no need, as the user still in send model, the state has remained

2024-12-19 03:20 UTC, stanleyyconsensys commented on packages/wallet-ui/src/components/ui/organism/Header/SendSummaryModal/SendSummaryModal.view.tsx
> +  handleBack: (amount: string, address: string) => void;
```suggestion
  handleBack: () => void;
```

2024-12-19 03:20 UTC, stanleyyconsensys commented on packages/wallet-ui/src/components/ui/molecule/AmountInput/AmountInput.view.tsx
>    useEffect(() => {
this block is no need, as setInputValue has fired in triggerOnChange

2024-12-19 03:20 UTC, stanleyyconsensys commented on packages/wallet-ui/src/components/ui/molecule/AmountInput/AmountInput.view.tsx
> +  }, [fetchTotalPrice]);
```suggestion
  }, [asset, inputValue, usdMode]);
```

remove the useCallback , but move it to useEffect for easier understand, that useeffect is only trigger when xxxx

2024-12-19 03:20 UTC, stanleyyconsensys commented on packages/wallet-ui/src/components/ui/molecule/AmountInput/AmountInput.view.tsx
> +  }, [resizeInput]);
```suggestion
  }, [inputValue]);

```
same comment as below, remove the useCallback

2024-12-19 03:20 UTC, stanleyyconsensys commented on packages/wallet-ui/src/components/ui/molecule/AmountInput/AmountInput.view.tsx
>        resizeInput();
```suggestion
```

this 2 can be removed, as they will triggered at onEffect

2025-01-30 12:55 UTC, khanti42 commented on packages/wallet-ui/src/components/ui/molecule/AmountInput/AmountInput.view.tsx
> +    if (value && asset.usdPrice) {
the max button should still work even if asset.usdPrice is not available I removed the if altogether.

2025-02-07 03:08 UTC, stanleyyconsensys approved these changes
In terms of allow return back, which seem okay to me, so i give pass on this PR

but during the testing i found 2 bugs
the send modal doesnt do validation and accept "." or "0", and it will have JS error screen if user type "." only

i suggest we can have to a validation on send modal (right now the validation is too simple)

And amount input seem fine, as it responsibly is just blocking non number char and convert USD to ETH

2025-02-12 22:08 UTC, khanti42 commented
Added a task in backlog regarding the validation (sf-804)

2025-02-12 22:17 UTC, merged