Feat/update starknet client lib
Consensys/starknet-snap pull request #94
Opened 2023-07-10 02:32 UTC by stanleyyconsensys

- migrate number.toBN to num.toBigInt
- migrate bulkTransaction to Invocations
- migrate verify and sign message format
- migrate stark.compileCalldata to CallData.compile
- upgrade starknet lib to 5.14.0
- remove old acc handle on ui and snap
- add tojson to fix bigint tojson
- remove deprecated acc and network
- update unit test

2023-07-10 14:47 UTC, Akaryatrh requested changes

2023-07-10 14:47 UTC, Akaryatrh commented on packages/starknet-snap/src/extractPublicKey.ts
> +    if (!accContract?.publicKey || num.toBigInt(accContract.publicKey) == constants.ZERO) {
Why double and not triple equality here?

2023-07-10 14:47 UTC, Akaryatrh commented on packages/starknet-snap/src/utils/keyPair.ts
> +  const addressKey = privateKey;
[optional] You may do this instead?
```suggestion
  const addressKey = grindKey(addressKey);
  return {
    addressKey,
    derivationPath: keyDeriver.path,
  };
```

2023-07-11 07:36 UTC, Akaryatrh approved these changes

2023-07-11 07:52 UTC, wantedsystem commented
Hello @stanleyyconsensys LGTM can you fix the build, lint and test job that is failing ?

2023-07-11 08:32 UTC, wantedsystem approved these changes

2023-07-11 11:21 UTC, merged